services:
  - type: web
    name: sijilati-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: STATIC_ROOT
        value: ./dist
      - key: DATA_ROOT
        value: ./data
