services:
  - type: web
    name: sijilati-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.mjs
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
